### ISSUE TITLE
trax.TraxException: Unable to connect to tracker  HQTrack/baseline

### ISSUE THREAD

**Issue by iostreambond** [jiawen-zhu/HQTrack#8]
I have configured the project, also I have modified the trackers.ini file as:

```
[HQTrack] # <tracker-name>
label = HQTrack
command = run_tracker_vot
protocol = traxpython
paths = /home/os_name/PycharmProjects/hq_track/VOTS23_workspace
```
Now when I am running the project using the following command:

```
~/PycharmProjects/hq_track/VOTS23_workspace$ bash run.sh
```

I am getting the exception as:

```
                      |                                                                                                                                              |   0% [00:00<?]Unable to connect to tracker
Traceback (most recent call last):
  File "/home/os_name/PycharmProjects/hq_track/venv_hqtrack/lib/python3.8/site-packages/vot/utilities/cli.py", line 445, in main
    do_evaluate(args)
  File "/home/os_name/PycharmProjects/hq_track/venv_hqtrack/lib/python3.8/site-packages/vot/utilities/cli.py", line 228, in do_evaluate
    run_experiment(experiment, tracker, workspace.dataset, config.force, config.persist)
  File "/home/os_name/PycharmProjects/hq_track/venv_hqtrack/lib/python3.8/site-packages/vot/experiment/__init__.py", line 345, in run_experiment
    experiment.execute(tracker, sequence, force=force, callback=progress)
  File "/home/os_name/PycharmProjects/hq_track/venv_hqtrack/lib/python3.8/site-packages/vot/experiment/multirun.py", line 146, in execute
    with self._get_runtime(tracker, sequence, self._multiobject) as runtime:
  File "/home/os_name/PycharmProjects/hq_track/venv_hqtrack/lib/python3.8/site-packages/vot/experiment/__init__.py", line 185, in _get_runtime
    if not runtime.multiobject:
  File "/home/os_name/PycharmProjects/hq_track/venv_hqtrack/lib/python3.8/site-packages/vot/tracker/trax.py", line 539, in multiobject
    self._connect()
  File "/home/os_name/PycharmProjects/hq_track/venv_hqtrack/lib/python3.8/site-packages/vot/tracker/trax.py", line 549, in _connect
    self._process = TrackerProcess(self._command, self._envvars, log=log, socket=self._socket, timeout=self._timeout)
  File "/home/os_name/PycharmProjects/hq_track/venv_hqtrack/lib/python3.8/site-packages/vot/tracker/trax.py", line 294, in __init__
    raise e
  File "/home/os_name/PycharmProjects/hq_track/venv_hqtrack/lib/python3.8/site-packages/vot/tracker/trax.py", line 287, in __init__
    self._client = Client(
  File "/home/os_name/PycharmProjects/hq_track/venv_hqtrack/lib/python3.8/site-packages/trax/client.py", line 66, in __init__
    raise TraxException("Unable to connect to tracker")
trax.TraxException: Unable to connect to tracker
 HQTrack/baseline     |                                                                                                                                              |   0% [00:00<?]
Packaging results for tracker HQTrack
                      |                                                                                                                                              |   0% [00:00<?]Results are not complete for experiment baseline, sequence animal
 Scanning             |▉                                                                                                                                         |   1% [00:00<00:21]Results are not complete for experiment baseline, sequence ants1
Results are not complete for experiment baseline, sequence bag
Results are not complete for experiment baseline, sequence basketball
Results are not complete for experiment baseline, sequence basketball-11
Results are not complete for experiment baseline, sequence beaker
Results are not complete for experiment baseline, sequence bear-6
 Scanning             |██████▋                                                                                                                                   |   5% [00:00<00:04]Results are not complete for experiment baseline, sequence bicycle
Results are not complete for experiment baseline, sequence bicycle-7
Results are not complete for experiment baseline, sequence bird-15
Results are not complete for experiment baseline, sequence bird-2
 Scanning             |██████████▌                                                                                                                               |   8% [00:00<00:04]Results are not complete for experiment baseline, sequence birds1
Results are not complete for experiment baseline, sequence boat
Results are not complete for experiment baseline, sequence bolt1
Results are not complete for experiment baseline, sequence book
Results are not complete for experiment baseline, sequence book-3
 Scanning             |███████████████▎                                                                                                                          |  11% [00:00<00:03]Results are not complete for experiment baseline, sequence bottle
Results are not complete for experiment baseline, sequence bubble
Results are not complete for experiment baseline, sequence bull
Results are not complete for experiment baseline, sequence bus
Results are not complete for experiment baseline, sequence bus-2
 Scanning             |████████████████████▏                                                                                                                     |  15% [00:00<00:02]Results are not complete for experiment baseline, sequence car
Results are not complete for experiment baseline, sequence car-9
Results are not complete for experiment baseline, sequence carchase
Results are not complete for experiment baseline, sequence cat
Results are not complete for experiment baseline, sequence cattle-13
 Scanning             |████████████████████████▉                                                                                                                 |  18% [00:00<00:03]Results are not complete for experiment baseline, sequence chameleon-20
Results are not complete for experiment baseline, sequence clownfish
Results are not complete for experiment baseline, sequence colorfish
Results are not complete for experiment baseline, sequence conduction1
Results are not complete for experiment baseline, sequence crab-18
Results are not complete for experiment baseline, sequence crab-6
Results are not complete for experiment baseline, sequence crabs1
Results are not complete for experiment baseline, sequence dancingshoe
 Scanning             |████████████████████████████████▌                                                                                                         |  24% [00:00<00:02]Results are not complete for experiment baseline, sequence deer
Results are not complete for experiment baseline, sequence diabolo
Results are not complete for experiment baseline, sequence diving
Results are not complete for experiment baseline, sequence dog
Results are not complete for experiment baseline, sequence dog-7
Results are not complete for experiment baseline, sequence dog1
 Scanning             |██████████████████████████████████████▎                                                                                                   |  28% [00:01<00:02]Results are not complete for experiment baseline, sequence dolphins
Results are not complete for experiment baseline, sequence domino_damselfish
Results are not complete for experiment baseline, sequence dragon
Results are not complete for experiment baseline, sequence drone
Results are not complete for experiment baseline, sequence drone1
Results are not complete for experiment baseline, sequence drone_across
 Scanning             |████████████████████████████████████████████                                                                                              |  32% [00:01<00:02]Results are not complete for experiment baseline, sequence duck
Results are not complete for experiment baseline, sequence f1
Results are not complete for experiment baseline, sequence fernando
Results are not complete for experiment baseline, sequence fish1
Results are not complete for experiment baseline, sequence fish2
Results are not complete for experiment baseline, sequence fishnet
Results are not complete for experiment baseline, sequence flag
Results are not complete for experiment baseline, sequence flag-3
 Scanning             |███████████████████████████████████████████████████▊                                                                                      |  38% [00:01<00:01]Results are not complete for experiment baseline, sequence flamingo1
Results are not complete for experiment baseline, sequence flyboard
Results are not complete for experiment baseline, sequence fox
Results are not complete for experiment baseline, sequence freesbiedog
Results are not complete for experiment baseline, sequence frisbee
Results are not complete for experiment baseline, sequence gametarget-7
 Scanning             |█████████████████████████████████████████████████████████▌                                                                                |  42% [00:01<00:01]Results are not complete for experiment baseline, sequence goldfish
Results are not complete for experiment baseline, sequence goldfish-3
Results are not complete for experiment baseline, sequence gorilla-13
Results are not complete for experiment baseline, sequence gymnastics1
Results are not complete for experiment baseline, sequence gymnastics3
 Scanning             |██████████████████████████████████████████████████████████████▎                                                                           |  45% [00:01<00:01]Results are not complete for experiment baseline, sequence hand
Results are not complete for experiment baseline, sequence hand-9
Results are not complete for experiment baseline, sequence hand2
Results are not complete for experiment baseline, sequence hand3
Results are not complete for experiment baseline, sequence handball2
Results are not complete for experiment baseline, sequence hat-1
Results are not complete for experiment baseline, sequence hat-5
 Scanning             |█████████████████████████████████████████████████████████████████████                                                                     |  50% [00:01<00:01]Results are not complete for experiment baseline, sequence helicopter
Results are not complete for experiment baseline, sequence houseride
Results are not complete for experiment baseline, sequence iceskater2
Results are not complete for experiment baseline, sequence juggling
Results are not complete for experiment baseline, sequence kangaroo
Results are not complete for experiment baseline, sequence kite-10
Results are not complete for experiment baseline, sequence leaves
 Scanning             |███████████████████████████████████████████████████████████████████████████▋                                                              |  55% [00:01<00:01]Results are not complete for experiment baseline, sequence licenseplate
Results are not complete for experiment baseline, sequence lion-12
Results are not complete for experiment baseline, sequence marathon
Results are not complete for experiment baseline, sequence matrix
Results are not complete for experiment baseline, sequence monkey-3
Results are not complete for experiment baseline, sequence monkey-9
 Scanning             |█████████████████████████████████████████████████████████████████████████████████▍                                                        |  59% [00:01<00:01]Results are not complete for experiment baseline, sequence moorish_idol
Results are not complete for experiment baseline, sequence motorcycle
Results are not complete for experiment baseline, sequence motorcycle-1
Results are not complete for experiment baseline, sequence motorcycle-18
Results are not complete for experiment baseline, sequence nature
Results are not complete for experiment baseline, sequence orangefish
 Scanning             |███████████████████████████████████████████████████████████████████████████████████████▏                                                  |  63% [00:02<00:01]Results are not complete for experiment baseline, sequence panda
Results are not complete for experiment baseline, sequence parkour
Results are not complete for experiment baseline, sequence person-12
Results are not complete for experiment baseline, sequence person-5
Results are not complete for experiment baseline, sequence pig-2
 Scanning             |████████████████████████████████████████████████████████████████████████████████████████████                                              |  67% [00:02<00:01]Results are not complete for experiment baseline, sequence pool-15
Results are not complete for experiment baseline, sequence rabbit
Results are not complete for experiment baseline, sequence rabbit-10
Results are not complete for experiment baseline, sequence rabbits
Results are not complete for experiment baseline, sequence racing-16
Results are not complete for experiment baseline, sequence robot
 Scanning             |█████████████████████████████████████████████████████████████████████████████████████████████████▊                                        |  71% [00:02<00:00]Results are not complete for experiment baseline, sequence robot-1
Results are not complete for experiment baseline, sequence robot-19
Results are not complete for experiment baseline, sequence robot-5
Results are not complete for experiment baseline, sequence rollerman
Results are not complete for experiment baseline, sequence run
 Scanning             |██████████████████████████████████████████████████████████████████████████████████████████████████████▌                                   |  74% [00:02<00:00]Results are not complete for experiment baseline, sequence sailing
Results are not complete for experiment baseline, sequence seagull
Results are not complete for experiment baseline, sequence seastar
Results are not complete for experiment baseline, sequence sepia-13
Results are not complete for experiment baseline, sequence sepia-8
 Scanning             |███████████████████████████████████████████████████████████████████████████████████████████████████████████▎                              |  78% [00:02<00:00]Results are not complete for experiment baseline, sequence shaking
Results are not complete for experiment baseline, sequence shark-2
Results are not complete for experiment baseline, sequence sheep-9
Results are not complete for experiment baseline, sequence singer3
Results are not complete for experiment baseline, sequence sitcom
Results are not complete for experiment baseline, sequence skateboard-8
 Scanning             |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                         |  82% [00:02<00:00]Results are not complete for experiment baseline, sequence skiing
Results are not complete for experiment baseline, sequence snake
Results are not complete for experiment baseline, sequence soccer1
Results are not complete for experiment baseline, sequence soldier
Results are not complete for experiment baseline, sequence squirrel
Results are not complete for experiment baseline, sequence stripedfish
Results are not complete for experiment baseline, sequence surfboard-12
 Scanning             |███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                  |  87% [00:03<00:00]Results are not complete for experiment baseline, sequence tank-16
Results are not complete for experiment baseline, sequence tank-9
Results are not complete for experiment baseline, sequence tennis
Results are not complete for experiment baseline, sequence tiger-4
Results are not complete for experiment baseline, sequence train-7
 Scanning             |████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌             |  90% [00:03<00:00]Results are not complete for experiment baseline, sequence transparent_fish
Results are not complete for experiment baseline, sequence uav1
Results are not complete for experiment baseline, sequence umbrella-19
Results are not complete for experiment baseline, sequence umbrella-9
Results are not complete for experiment baseline, sequence volleyball
 Scanning             |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍        |  94% [00:03<00:00]Results are not complete for experiment baseline, sequence volleyball-18
Results are not complete for experiment baseline, sequence volleyball-19
Results are not complete for experiment baseline, sequence whitefish
Results are not complete for experiment baseline, sequence wiper
Results are not complete for experiment baseline, sequence wubble_bubble
Results are not complete for experiment baseline, sequence yoyo-7
 Scanning             |███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  |  98% [00:03<00:00]Results are not complete for experiment baseline, sequence zebra-10
Results are not complete for experiment baseline, sequence zebra-16
Results are not complete for experiment baseline, sequence zebrafish1
 Scanning             |██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100% [00:03<00:00]
Unable to continue, experiments not complete
```

I request you to kindly help me in solving this exception.

**Comment by jiawen-zhu** [comment]
Hi~
It looks like your vot-toolkit is not running successfully.
I suggest you check that the dataset as well as the paths are configured correctly, as well as that the project and model paths are correct, and that the run path is correct.
In addition, it is recommended to first run：
`python run_tracker_vot.py `
to complete the debug process.

**Comment by jiaxi0030** [comment]
![image](https://github.com/jiawen-zhu/HQTrack/assets/92349729/5242bb41-a40c-4b90-8015-9b8e2fdc5661)
Thank you for your efforts. however, I encountered issues while running the model.
What is the correct result after entering  ”python run_tracker_vot.py “. ? I keep getting stuck here.

**Comment by sebastianopazo1** [comment]
I have the same issue. Could you solve it?
Great job with HQTrack by the way!

**Comment by IritaSee** [comment]
Hello everyone, maybe the tracker (`python run_tracker_vot.py`) need to be available when we run the `.sh` file (so run in on a separate terminal)

at least it will eliminate the "unable to connect" error, 

If another error occur, at this point we should be able to see the log file, that should be helpful! ^^
